### ISSUE TITLE
auto login

### ISSUE THREAD

**Issue by RaoClara324** [anilgulecha/shellinabox#5]
hi, 
Do you have details on how to use shellinabox to auto login ubuntu system?? The inf here is quite limited. I really appreciate it. Thanks

**Comment by anilgulecha** [comment]
you have to add ?u=<user>&p=<password> to the shellinabox url.

**Comment by RaoClara324** [comment]
yes. I fixed it. Thanks a lot.Your code is awesome!

**Comment by jjsmith07** [comment]
Does that really work, tried it on a centos system and could not get it to work. I am still getting prompted.

**Comment by RaoClara324** [comment]
I only tried autologin in my webpage on the ubuntu system (lastest
version), it worked. not sure about centos system...actually I never used
centos system before. not sure if I can help you that part...

**Comment by jjsmith07** [comment]
Hi Clara324,
Thanks for your reply.
Do you mind sharing a sample of how your url works and the parameters you use to start shellinaboxd, so I can compare with what I have?

Thanks!

**Comment by RaoClara324** [comment]
sure.I have local webpages and will tell you on how to install it.  But The
files, for local test, are working. but I have no chance to test it on a
real server since I never got the feedback from the administer.  so I am
not sure if it really works on your case. Can I send you the files this
weekend?

**Comment by sgohl** [comment]
I am also trying to get auto login working on CentOS 7 (within docker)
It's for temporary local development docker containers for convenience, so no security needed at all.
Can't I just set the login program to be /bin/bash or so?

**Comment by roozgar** [comment]
the "?u=xxx&p=yyy" not working for me
is there any extra option for activate auto login !?

peiman@ubuntu:~$ shellinaboxd -v
[server] Version 2.20

**Comment by johnorjias** [comment]
not working for me either

**Comment by sgohl** [comment]
@johnorjias try goTTY: https://github.com/yudai/gotty

**Comment by anilgulecha** [comment]
Yes, gotty or ttyd is the way to go these days. They provide everything in shellinabox and more perhaps.
